### ISSUE TITLE
Vue 3 TypeScript Error: TypeError: Cannot read property 'isCookieAvailable' of undefined

### ISSUE THREAD

**Issue by roberttolton** [anish2690/vue-cookie-next#7]
Regarding the following line:

https://github.com/anish2690/vue-cookie-next/blob/56a4da3bf0085ad7656659a70d13e82634e6756a/src/VueCookieNext.ts#L178

Using within an `onMounted` hook within the `setup` method, `this` is undefined.

**Comment by TapanM** [comment]
same issue. do we have any workaround for this?

**Comment by roberttolton** [comment]
@TapanM I just switched to https://github.com/js-cookie/js-cookie

**Comment by anish2690** [comment]
@roberttolton @TapanM i think this should be already fixed, not able to reproduce it. If you still facing issue please post reproduction repo link.
